---
title: "Thampi et al. 2017"
author: "Sophie Wulfing"
date: "9/28/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(deSolve)
library(tidyverse)
library(ggplot2)

```

# Model Setup


```{r}
closed.coral.model1 <- function (t, y, params) {
  ## first extract the state variables
  M <- y[1]
  C <- y[2]
  P <- y[3]
  X <- y[4]
  #TT <- y[5]
  
  ## now extract the parameters
  alpha <- params["alpha"]
  gamma <- params["gamma"]
  r <- params["r"]
  d <- params["d"]
  kappa <- params["kappa"]
  sigma <- params["sigma"]
  s <- params["s"]
  j <- params["j"]
  phi <- params["phi"]
  TT <- 1 - M - C
  
  ## now code the model equations
  dMdt <- alpha*M*C - (P*M)/(M+TT) + gamma*M*TT
  dCdt <- r*TT*C - d*C - alpha*M*C
  #dTTdt <- (P*M)/(M+TT) - gamma*M*TT - r*TT*C + d*C
  dPdt <- s*P*(1-(P/C)) - sigma*P*(1-X)
  dXdt <- kappa*X*(1-X)*(-1+j*(1-C)-sigma*P*(1-X)+phi *(2*X-1))
  
  ## combine results into a single vector
  dydt <- c(dMdt,dCdt, dPdt, dXdt)
  ## return result as a list!
  
  list(dydt)
}

closed.coral.model2 <- function (t, y, params) {
  ## first extract the state variables
  M <- y[1]
  C <- y[2]
  P <- y[3]
  X <- y[4]
  #TT <- y[5]
  
  ## now extract the parameters
  alpha <- params["alpha"]
  gamma <- params["gamma"]
  r <- params["r"]
  d <- params["d"]
  kappa <- params["kappa"]
  sigma <- params["sigma"]
  s <- params["s"]
  j <- params["j"]
  phi <- params["phi"]
  z <- params["z"]
  TT <- 1 - M - C
  
  ## now code the model equations
  dMdt <- alpha*M*C - (P*M)/(M+TT) + gamma*M*TT
  dCdt <- r*TT*C - d*C - alpha*M*C
  #dTTdt <- (P*M)/(M+TT) - gamma*M*TT - r*TT*C + d*C
  dPdt <- s*P*(1-(P/(1-z*C))) - sigma*P*(1-X)
  dXdt <- kappa*X*(1-X)*(-1+j*(1-C)-sigma*P*(1-X)+phi *(2*X-1))
  
  ## combine results into a single vector
  dydt <- c(dMdt,dCdt, dPdt, dXdt)
  
  ## return result as a list!
  list(dydt)
}
```

# Graphs included in paper

```{r, echo=FALSE, fig.cap = "Fig 3a in Thampi paper. S = 0, sigma = 0.1", out.width = "50%", fig.show="hold"}
#paper changes sigma and s
parms1 <- c(alpha = .1, gamma = .8, r = 1, d = .44, kappa = 1.014, sigma = .1, s = 0, j = 1.68, phi = .2)
parms2 <- c(alpha = .1, gamma = .8, r = 1, d = .44, kappa = 1.014, sigma = .1, s = 0, j = 1.68, phi = .2, z = .5)

times <- seq(from = 80, to = 180, by = 1)
xstart <- c(M = .3, C = .6, P = .2, X = .1) #No initial condition listed for TT

ode(
  func=closed.coral.model1,
  y=xstart,
  times=times,
  parms=parms1
) %>%
  as.data.frame() -> out1

out1 %>%
 gather(variable,value,-time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
  geom_line(size=2) +
  scale_x_log10() +
  theme(legend.title=NULL) +
  theme_classic() +
  scale_color_discrete(name = "", labels = c("Live Coral", "Macroalgae", "Parrotfish", "Human Operation")) +
  labs(title = "K(C) = C", x='Time(Years)', y='Proportion of Population')

ode(
  func=closed.coral.model2,
  y=xstart,
  times=times,
  parms=parms2
) %>%
  as.data.frame() -> out2

out2 %>%
  gather(variable,value,-time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
  geom_line(size=2) +
  scale_x_log10() +
  theme(legend.title=NULL) +
  theme_classic() +
  scale_color_discrete(name = "", labels = c("Live Coral", "Macroalgae", "Parrotfish", "Human Operation")) +
  labs(title = "K(C) = 1-zC", x='Time(Years)', y='Proportion of Population')

```

```{r, echo=FALSE, fig.cap = "Fig 3b in Thampi paper. S = 0, sigma = 0.15", out.width = "50%", fig.show="hold"}
#paper changes sigma and s
parms1 <- c(alpha = .1, gamma = .8, r = 1, d = .44, kappa = 1.014, sigma = .15, s = 0, j = 1.68, phi = .2)
parms2 <- c(alpha = .1, gamma = .8, r = 1, d = .44, kappa = 1.014, sigma = .15, s = 0, j = 1.68, phi = .2, z = .5)

times <- seq(from = 0, to = 100, by = 1)
xstart <- c(M = .3, C = .6, P = .2, X = .1) #No initial condition listed for TT

ode(
  func=closed.coral.model1,
  y=xstart,
  times=times,
  parms=parms1
) %>%
  as.data.frame() -> out1

out1 %>%
 gather(variable,value,-time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
  geom_line(size=2) +
  theme(legend.title=NULL) +
  theme_classic() +
  scale_color_discrete(name = "", labels = c("Live Coral", "Macroalgae", "Parrotfish", "Human Operation")) +
  labs(title = "K(C) = C", x='Time(Years)', y='Proportion of Population')

ode(
  func=closed.coral.model2,
  y=xstart,
  times=times,
  parms=parms2
) %>%
  as.data.frame() -> out2

out2 %>%
  gather(variable,value,-time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
  geom_line(size=2) +
  theme(legend.title=NULL) +
  theme_classic() +
  scale_color_discrete(name = "", labels = c("Live Coral", "Macroalgae", "Parrotfish", "Human Operation")) +
  labs(title = "K(C) = 1-zC", x='Time(Years)', y='Proportion of Population')

```

```{r, echo=FALSE, fig.cap = "Fig 3c in Thampi paper. S = 0.3, sigma = 0.05", out.width = "50%", fig.show="hold"}
#paper changes sigma and s
parms1 <- c(alpha = .1, gamma = .8, r = 1, d = .44, kappa = 1.014, sigma = .05, s = .3, j = 1.68, phi = .2)
parms2 <- c(alpha = .1, gamma = .8, r = 1, d = .44, kappa = 1.014, sigma = .05, s = .3, j = 1.68, phi = .2, z = .5)

times <- seq(from = 80, to = 180, by = 1)
xstart <- c(M = .3, C = .6, P = .2, X = .1) #No initial condition listed for TT

ode(
  func=closed.coral.model1,
  y=xstart,
  times=times,
  parms=parms1
) %>%
  as.data.frame() -> out1

out1 %>%
 gather(variable,value,-time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
  geom_line(size=2) +
  theme(legend.title=NULL) +
  theme_classic() +
  scale_color_discrete(name = "", labels = c("Live Coral", "Macroalgae", "Parrotfish", "Human Operation")) +
  labs(title = "K(C) = C", x='Time(Years)', y='Proportion of Population')

ode(
  func=closed.coral.model2,
  y=xstart,
  times=times,
  parms=parms2
) %>%
  as.data.frame() -> out2

out2 %>%
  gather(variable,value,-time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
  geom_line(size=2) +
  theme(legend.title=NULL) +
  theme_classic() +
  scale_color_discrete(name = "", labels = c("Live Coral", "Macroalgae", "Parrotfish", "Human Operation")) +
  labs(title = "K(C) = 1-zC", x='Time(Years)', y='Proportion of Population')

```

```{r, echo=FALSE, fig.cap = "Fig 3d in Thampi paper. S = 0.2, sigma = 0.5", out.width = "50%", fig.show="hold"}
#paper changes sigma and s
parms1 <- c(alpha = .1, gamma = .8, r = 1, d = .44, kappa = 1.014, sigma = .5, s = .2, j = 1.68, phi = .2)
parms2 <- c(alpha = .1, gamma = .8, r = 1, d = .44, kappa = 1.014, sigma = .5, s = .2, j = 1.68, phi = .2, z = .5)

times <- seq(from = 350, to = 450, by = 1)
xstart <- c(M = .3, C = .6, P = .2, X = .1) #No initial condition listed for TT

ode(
  func=closed.coral.model1,
  y=xstart,
  times=times,
  parms=parms1
) %>%
  as.data.frame() -> out1

out1 %>%
 gather(variable,value,-time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
  geom_line(size=2) +
  theme(legend.title=NULL) +
  theme_classic() +
  scale_color_discrete(name = "", labels = c("Live Coral", "Macroalgae", "Parrotfish", "Human Operation")) +
  labs(title = "K(C) = C", x='Time(Years)', y='Proportion of Population')

ode(
  func=closed.coral.model2,
  y=xstart,
  times=times,
  parms=parms2
) %>%
  as.data.frame() -> out2

out2 %>%
  gather(variable,value,-time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
  geom_line(size=2) +
  theme(legend.title=NULL) +
  theme_classic() +
  scale_color_discrete(name = "", labels = c("Live Coral", "Macroalgae", "Parrotfish", "Human Operation")) +
  labs(title = "K(C) = 1-zC", x='Time(Years)', y='Proportion of Population')

```

```{r, echo=FALSE, fig.cap = "Fig 3e in Thampi paper. S = 0.4, sigma = 0.4", out.width = "50%", fig.show="hold"}
#paper changes sigma and s
parms1 <- c(alpha = .1, gamma = .8, r = 1, d = .44, kappa = 1.014, sigma = .4, s = .4, j = 1.68, phi = .2)
parms2 <- c(alpha = .1, gamma = .8, r = 1, d = .44, kappa = 1.014, sigma = .4, s = .4, j = 1.68, phi = .2, z = .5)

times <- seq(from = 450, to = 550, by = 1)
xstart <- c(M = .3, C = .6, P = .2, X = .1) #No initial condition listed for TT

ode(
  func=closed.coral.model1,
  y=xstart,
  times=times,
  parms=parms1
) %>%
  as.data.frame() -> out1

out1 %>%
 gather(variable,value,-time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
  geom_line(size=2) +
  theme(legend.title=NULL) +
  theme_classic() +
  scale_color_discrete(name = "", labels = c("Live Coral", "Macroalgae", "Parrotfish", "Human Operation")) +
  labs(title = "K(C) = C", x='Time(Years)', y='Proportion of Population')

ode(
  func=closed.coral.model2,
  y=xstart,
  times=times,
  parms=parms2
) %>%
  as.data.frame() -> out2

out2 %>%
  gather(variable,value,-time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
  geom_line(size=2) +
  theme(legend.title=NULL) +
  theme_classic() +
  scale_color_discrete(name = "", labels = c("Live Coral", "Macroalgae", "Parrotfish", "Human Operation")) +
  labs(title = "K(C) = 1-zC", x='Time(Years)', y='Proportion of Population')

```

```{r, echo=FALSE, fig.cap = "Fig 3f in Thampi paper. S = 0.35, sigma = 0.5", out.width = "50%", fig.show="hold"}
#paper changes sigma and s
parms1 <- c(alpha = .1, gamma = .8, r = 1, d = .44, kappa = 1.014, sigma = .5, s = .35, j = 1.68, phi = .2)
parms2 <- c(alpha = .1, gamma = .8, r = 1, d = .44, kappa = 1.014, sigma = .5, s = .35, j = 1.68, phi = .2, z = .5)

times <- seq(from = 250, to = 350, by = 1)
xstart <- c(M = .3, C = .6, P = .2, X = .1) #No initial condition listed for TT

ode(
  func=closed.coral.model1,
  y=xstart,
  times=times,
  parms=parms1
) %>%
  as.data.frame() -> out1

out1 %>%
 gather(variable,value,-time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
  geom_line(size=2) +
  theme(legend.title=NULL) +
  theme_classic() +
  scale_color_discrete(name = "", labels = c("Live Coral", "Macroalgae", "Parrotfish", "Human Operation")) +
  labs(title = "K(C) = C", x='Time(Years)', y='Proportion of Population')

ode(
  func=closed.coral.model2,
  y=xstart,
  times=times,
  parms=parms2
) %>%
  as.data.frame() -> out2

out2 %>%
  gather(variable,value,-time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
  geom_line(size=2) +
  theme(legend.title=NULL) +
  theme_classic() +
  scale_color_discrete(name = "", labels = c("Live Coral", "Macroalgae", "Parrotfish", "Human Operation")) +
  labs(title = "K(C) = 1-zC", x='Time(Years)', y='Proportion of Population')

```
