---
title: "JNC"
author: "Sophie Wulfing"
date: "2022-11-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

setwd("C:/Users/sophi/Documents/GitHub/UNH_Docs/Proposal/Soc_Ecol_Model")

library(deSolve)
library(tidyverse)
library(ggplot2)
library(gridExtra)
```


```{r Bauch.Model, fig.cap = "Original Bauch Model"}
Bauch.Model <- function (t, y, params) {
  ## first extract the state variables
  P <- y[1] #Fish Pop var
  X <- y[2] #conservationist var

  #TT <- y[5]
  
  ## now extract the parameters
  R <- params["R"] # Net growth/fecundity
  s <- params["s"] # supply and demand
  h <- params["h"] # Harvesting efficiency
  k <- params["k"] # Social learning rate
  w <- params["w"] # conservation costs
  c <- params["c"] # rarity valuation param
  d <- params["d"] # social norm strength
  
  ## now code the model equations
  dPdt <- R * P * (1-P) - (h * P * (1-X))/(P+s)
  dXdt <- k * X * (1-X) * (d*(2*X-1) + 1/(P+c) - w)
  
  ## combine results into a single vector
  dydt <- c(dPdt, dXdt)
  ## return result as a list!
  
  list(dydt)
}

params_Bauch <- c(R = 0.06, s = 0.8, h = 0.1, k = 0.17, w = 1, c = 0.6, d = 0.3)

times <- seq(from = 0, to = 1000, by = 1)
xstart <- c(P = 0.406, X = .24) # See supplemental data for other starting params

ode(
  func=Bauch.Model,
  y=xstart,
  times=times,
  parms=params_Bauch
) %>%
  as.data.frame() -> out1

out1 %>%
  gather(variable,value,-time) %>%
  ggplot(aes(x=time,y=value,color=variable))+
  geom_line(size=2)+
  theme_classic()+
  labs(x='time (yr)',y='pop')

```

<!-- Notes: Still worried about interaction term. Don't think this is correct because mechanism isn't specified and we just added interaction terms.  -->

See derivation in notes but this is the new equations (still unsure about interaction terms):

$\frac{dP_1}{dt} = r_1P_1(1-P_1)-\frac{h_1*P_1(1-X_1)}{P_1 + s_1} -e_1P_1 + i_1P_2$

$\frac{dP_2}{dt} = r_2P_2(1-P_2)-\frac{h_2*P_2(1-X_2)}{P_2 + s_2} -e_2P_2 + i_2P_1$

$\frac{dX_1}{dt} =  k_1X_1(1-X_1) [\frac{1}{P_1+c_1} - w_1 + d_1(2X_1 - 1)] - prop_1X_1(2X_2 - 1)^2 + prop_1(1-X_1)(2X_2 - 1)^2$

$\frac{dX_2}{dt} = k_2x_2(1-X_2)  [\frac{1}{P_2+c_2} - w_2 + d_2(2X_2 - 1)] - prop_2X_2(2X_1 - 1)^2 + prop_2(1-X_2)(2X_1 - 1)^2$


```{r Bauch.Coupled, fig.cap = "New Model with default paramters"}
Bauch.Coupled <- function (t, y, params) {
  ## first extract the state variables
  P_1 <- y[1] #Fish Pop var
  P_2 <- y[2] #Fish Pop var
  X_1 <- y[3] #conservationist var
  X_2 <- y[4] #conservationist var

  #TT <- y[5]
  
  ## now extract the parameters
  R_1 <- params["R_1"] # Net growth/fecundity
  s_1 <- params["s_1"] # supply and demand
  h_1 <- params["h_1"] # Harvesting efficiency
  k_1 <- params["k_1"] # Social learning rate
  w_1 <- params["w_1"] # conservation costs
  c_1 <- params["c_1"] # rarity valuation param
  d_1 <- params["d_1"] # social norm strength
  
  R_2 <- params["R_2"] # Net growth/fecundity
  s_2 <- params["s_2"] # supply and demand
  h_2 <- params["h_2"] # Harvesting efficiency
  k_2 <- params["k_2"] # Social learning rate
  w_2 <- params["w_2"] # conservation costs
  c_2 <- params["c_2"] # rarity valuation param
  d_2 <- params["d_2"] # social norm strength 
  
  e_1 <- params["e_1"] # Outflow of fish pop1
  e_2 <- params["e_2"] # Outflow of fish pop2
  i_1 <- params["i_1"] # Inflow of fish from pop 2 to pop 1
  i_2 <- params["i_2"] # Inflow of fish from pop 1 to pop 2
  prop_1 <- params["prop_1"] # Influence of pop 2 on pop 1
  prop_2 <- params["prop_2"] # Influence of pop 1 on pop 2
  
  ## now code the model equations
  dP_1dt <-  R_1 * P_1 * (1-P_1) - (h_1 * P_1 * (1-X_1))/(P_1+s_1) -  e_1 * P_1 + i_1 * P_2
  dP_2dt <-  R_2 * P_2 * (1-P_2) - (h_2 * P_2 * (1-X_2))/(P_2+s_2) -  e_2 * P_2 + i_2 * P_1
  
  dX_1dt <-  k_1 * X_1 * (1-X_1) *(1/(P_1 + c_1) - w_1 + d_1*(2*X_1 - 1)) - prop_1 * X_1 * ((2* X_2 - 1)^2) + prop_1 * (1 - X_1) * ((2* X_2 - 1)^2)
  dX_2dt <- k_2 * X_2 * (1-X_2) *(1/(P_2 + c_2) - w_2 + d_2*(2*X_2 - 1)) - prop_2 * X_2 * ((2* X_1 - 1)^2) + prop_2 * (1 - X_2) * ((2* X_1 - 1)^2)
  
  ## combine results into a single vector
  dydt <- c(dP_1dt, dP_2dt, dX_1dt, dX_2dt)
  ## return result as a list!
  
  list(dydt)
}

params_Bauch <- c(R_1 = 0.06, s_1 = 0.8, h_1 = 0.075, k_1 = 0.17, w_1 = 0.35, c_1 = 0.6, d_1 = 0.5, e_1 = 0.05, i_1 = 0.05, prop_1 = 0.1,
                  R_2 = 0.06, s_2 = 0.8, h_2 = 0.075, k_2 = 0.17, w_2 = 0.35, c_2 = 0.6, d_2 = 0.5, e_2 = 0.05, i_2 = 0.05, prop_2 = 0.1)

times <- seq(from = 0, to = 100, by = .1)
xstart <- c(P_1 = 0.406, P_2 = 0.406, X_1 = .24, X_2 = .24) # See supplemental data for other starting params

ode(
  func=Bauch.Coupled,
  y=xstart,
  times=times,
  parms=params_Bauch
) %>%
  as.data.frame() -> out_Coupled

out_Coupled %>%
  gather(variable,value,-time) %>%
  ggplot(aes(x=time,y=value,color=variable))+
  geom_line(size=1)+
  theme_classic()+
  labs(x='time (yr)',y='pop')

```


```{r fxnBauch.ParamR}
# params_Default <- data.frame(R = 0.06, s = 0.8, h = 0.075, k = 0.17, w = 0.35, c = 0.6, d = 0.5, roe = 1)
# params_Bauch <- c(R_1 = 0.06, s_1 = 0.8, h_1 = 0.075, k_1 = 0.17, w_1 = 0.35, c_1 = 0.6, d_1 = 0.5, roe_1 = 1,
#                   R_2 = 0.06, s_2 = 0.8, h_2 = 0.075, k_2 = 0.17, w_2 = 0.35, c_2 = 0.6, d_2 = 0.125, roe_2 = 1)

# min <- 0
# max <- 1
# i <- 1
# param <- 8


#Note: in this function, I am changing BOTH populations' paramters. Should I try just changing one?
param_ranges <- function(param, max, min){
  #Generate list of ranges
  new_param <- seq(from=min, to=max, length.out=5)
  plotList <- list()
  
  #Change params to each quartile for graphs 1-5
  for(i in 1:length(new_param)){
    params_Default <- data.frame(R = 0.06, s = .8, h = 0.075, k = 0.17, w = 0.35, c = 0.6, d = 0.5, e = .05, i = .05, prop = .1)
    #ASSIGN OLD PARAMS TO BE NEW SEQUENCE
    params_Default[param] <- new_param[i]
    params_Bauch <- c(R_1 = params_Default$R, s_1 = params_Default$s, h_1 = params_Default$h, k_1 = params_Default$k,
                      w_1 = params_Default$w, c_1 = params_Default$c, d_1 = params_Default$d, e_1 = params_Default$e, i_1 = params_Default$i,
                      prop_1 =  params_Default$prop,
                      R_2 = params_Default$R, s_2 = params_Default$s, h_2 = params_Default$h, k_2 = params_Default$k,
                      w_2 = params_Default$w, c_2 =params_Default$c, d_2 = params_Default$d,  e_2 = params_Default$e, i_2 = params_Default$i,
                      prop_2 = params_Default$prop)
    
    times <- seq(from = 0, to = 100, by = 1)
    xstart <- c(P_1 = 0.406, P_2 = 0.406, X_1 = .24, X_2 = .24) #See supplemental for other starting params

    ode(
      func=Bauch.Coupled,
      y=xstart,
      times=times,
      parms=params_Bauch
    ) %>%
      as.data.frame() -> out_Diff

    p <- out_Diff %>%
      gather(variable,value,-time) %>%
      ggplot(aes(x=time,y=value,color=variable))+
      geom_line(size=1)+
      theme_classic()+
      labs(x='time (yr)',y='pop')
    plotList[[i]] <- p
  }
  
  #Now assigning the final graph to give the two populations the max and min of the paramters
    params_Default <- data.frame(R = 0.06, s = .8, h = 0.075, k = 0.17, w = 0.35, c = 0.6, d = 0.5, e = .05, i = 0.05, prop = .1)
    #ASSIGN OLD PARAMS TO BE NEW SEQUENCE
    params_Bauch <- c(R_1 = params_Default$R, s_1 = params_Default$s, h_1 = params_Default$h, k_1 = params_Default$k,
                      w_1 = params_Default$w, c_1 = params_Default$c, d_1 = params_Default$d, e_1 = params_Default$e, i_1 = params_Default$i,
                      prop_1 =  params_Default$prop,
                      R_2 = params_Default$R, s_2 = params_Default$s, h_2 = params_Default$h, k_2 = params_Default$k,
                      w_2 = params_Default$w, c_2 = params_Default$c, d_2 = params_Default$d, e_2 = params_Default$e, i_2 = params_Default$i,
                      prop_2 = params_Default$prop)
    params_Bauch[param] <- max
    params_Bauch[(param + 10)] <- min
    
    times <- seq(from = 0, to = 100, by = 1)
    xstart <- c(P_1 = 0.406, P_2 = 0.406, X_1 = .24, X_2 = .24) #See supplemental for other starting params

    ode(
      func=Bauch.Coupled,
      y=xstart,
      times=times,
      parms=params_Bauch
    ) %>%
      as.data.frame() -> out_Diff

    p <- out_Diff %>%
      gather(variable,value,-time) %>%
      ggplot(aes(x=time,y=value,color=variable))+
      geom_line(size=1)+
      theme_classic()+
      labs(x='time (yr)',y='pop')
    plotList[[6]] <- p
  
  
  
  do.call("grid.arrange", c(plotList, ncol=2))
}
  

```

```{r R, fig.cap= "R - Net growth/fecundity, range 0 to 1"}
param_ranges(1, 1, 0)
```

\newpage

```{r s, fig.cap = "S - supply and demand, range 0.1 to 1"}
param_ranges(2, 1, 0.1)
```

\newpage

```{r h, fig.cap = "h - Harvesting efficiency, range 0 to 0.1. Note, default is .075"}
param_ranges(3, 0.1, 0)
```

\newpage

```{r k, fig.cap = "K - Social learning rate 0 to 1"}
param_ranges(4, 1, 0)
```

\newpage

```{r w, fig.cap = "w - conservation costs"}
param_ranges(5, 1, 0)
```

\newpage

```{r c, fig.cap = "c - rarity valuation param"}
param_ranges(6, 1, 0)
```

\newpage

```{r d, fig.cap = "d - social norm strength "}
param_ranges(7, 1, 0)
```

\newpage

```{r e, fig.cap = "e - fish emigration"}
param_ranges(8, 1, 0)
```

\newpage

```{r i, fig.cap = "i - fish immigration"}
param_ranges(9, 1, 0)
```

\newpage

```{r prop, fig.cap = "prop - Population influence on the other"}
param_ranges(10, 1, 0)
```