---
title: "AgeInStage"
author: "Sophie Wulfing"
date: "2023-03-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, dev="cairo_pdf")
#knitr::write_bib look into
setwd("C:/Users/sophi/Documents/GitHub/UNH_Docs/Proposal/Mtx_Model")

library(tinytex)
library(matlib)
library(ggplot2)
library(quadprog) #cite
library(gridtext)
library(popbio) #cite
library(knitr)
library(gridExtra)
library(RColorBrewer) 
#library(rPref) #Double check what this is doing. Maybe cite?
library(tidyr)
library(dplyr)
library(ggpubr)
library(bookdown)
library(kableExtra)
library(Rage)


# #Raw data n supplemental. ASK
# in-stage bar graph goes in paper
# in stage management scenarios will definitely be supplemental
# Check out ecological modelling journal
# Write about stable stage cause I don't think you do
# Citations! Also check ahilya table
# APPENDIX!
# MAKE FIG CAPS FOR EVERYTHING AND EDIT FIGS.



observedData <- as.matrix(data.frame(read.csv("RaberinaryBenbow2012Calcs.csv")))
observedStageMatrix <- observedData[1:13, 2:5]
```

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r FXNoverallsurvive}
survivability <- function(increase){
    #Calculate survivability for each staege and increase by x%
    NewMtx <- (A * increase) + A
    
    for(i in 1:ncol(NewMtx)-1){
      if(sum(NewMtx[,i]) > 1 | NewMtx[4,4] > 1){
        return(NA)
      }}
    return(NewMtx)
}


#This is stupid but it just forces R to stop writing things as complex numbers
f <- function(x) {
   if (all(Im(z <- zapsmall(x))==0)) as.numeric(z) else x
}

real_check <- function(mtx){
  if(sum(mtx[,1]) > 1 | sum(mtx[,2]) > 1 | sum(mtx[,3]) > 1 | mtx[4,4] > 1){
    return(NA)
  }
  else{return(mtx)}
}

```

```{r FXNmatrixprint, results = 'asis'}
write_matex <- function(x) {
  begin <- "$$\\begin{bmatrix}"
  end <- "\\end{bmatrix}$$"
  X <-
    apply(x, 1, function(x) {
      paste(
        paste(x, collapse = "&"),
        "\\\\"
      )
    })
  writeLines(c(begin, X, end))
}

```

```{r QuadProg, echo = FALSE}
#Make Z
z <- matrix(t(observedStageMatrix[2:11,]), ncol = 1, nrow = 40, byrow = TRUE)
#z

#Make M
m <- matrix(, nrow = nrow(z) , ncol = 8)
for(i in 1:(nrow(observedStageMatrix)-3)){
  m[(4 * (i-1) + 1):(4 * i),] <- matrix(c(observedStageMatrix[i,1], 0, 0, 0, 0, 0, observedStageMatrix[i,4], 0,
                                          0, observedStageMatrix[i,1], observedStageMatrix[i,2], 0, 0, 0, 0, 0,
                                          0, 0, 0, observedStageMatrix[i,2], observedStageMatrix[i,3], 0, 0, 0,
                                          0, 0, 0, 0, 0, observedStageMatrix[i,3], 0, observedStageMatrix[i,4]),
                                        nrow = 4, byrow = TRUE)
  #m
}

#Make C
c <- matrix(c(diag(8) * (-1), 
              1, 1, 0, 0, 0, 0, 0, 0,
              0, 0, 1, 1, 0, 0, 0, 0,
              0, 0, 0, 0, 1, 1, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 1), nrow = 12, ncol = 8, byrow = TRUE)
#c
#Make b
b <- matrix(c(rep(0,8), rep(1,4)), nrow = 12, ncol = 1, byrow = TRUE)

#Make P
#p <- matrix(, nrow = 8, ncol = 1, byrow = TRUE) #vector(p1, g1, p2, g2, p3, g3, f4, p4)

#Make mtx G and vector x
g <- t(m) %*% m
f_t <- -(t(-z) %*% m)

qp <- solve.QP(Dmat = g, dvec = f_t, Amat = -t(c), bvec = -t(b))#, factorized = FALSE)


A <- matrix(c(qp$solution[1], 0, 0, qp$solution[7],
                 qp$solution[2], qp$solution[3], 0, 0,
                 0, qp$solution[4], qp$solution[5], 0,
                 0, 0, qp$solution[6], qp$solution[8]), byrow = TRUE, nrow = 4, ncol = 4)
#A
```

```{r LifeHistory, results = 'asis', echo = FALSE}

LifeHistory <- read.csv("OcyaneaLifeHistory.csv")
#LifeHistory
knitr::kable(LifeHistory, format = "latex", booktabs = TRUE, caption = "(ref:lifehistory) \\label{LifeHistory}") %>%
  kable_styling(latex_options="scale_down")

```

```{r MtxCalcs, results = 'asis', echo = FALSE}
ages <- data.frame(matrix(data = NA, nrow = 4, ncol = 3))
colnames(ages) <- c("Stage", "Duration_New", "Variance")
for(i in 1:nrow(A)){
  ages$Stage[i] <- i
  ages$Duration_New[i] <- 1/(1-A[i,i])
  ages$Variance[i] <- A[i,i]/(1-A[i,i])^2
}

knitr::kable(ages, format = "latex", booktabs = TRUE)

```

```{r ragepackage, echo = FALSE}
library(Rage)
matU <- mpm_split(A)$matU
matU[1,1] <- A[1,1]

matR <- mpm_split(A)$matF
matR[1,1] <- 0

#mpm_standardize is the opposite of mpm_split

```

```{r lifeExp, results = 'asis', echo = FALSE}
lem <- life_expect_mean(matU, start = 1L)
lev <- life_expect_var(matU, start = 1L)
#le <- life_expect(matU, start = 1L)
lon <- longevity(matU, start = 1L, x_max = 1000, lx_crit = 0.01)

lifeexptable <- data.frame(matrix(, ncol = 2, nrow = 3) )

lifeexptable[1] <-  c("Life Expectancy", "Life Exp Variance", "longevity")
lifeexptable[2] <- c(lem, lev, lon)

knitr::kable(lifeexptable, format = "latex", booktabs = TRUE)

```

```{r AgeRepro, results = 'asis', echo = FALSE}
prob <- mature_prob(matU, matR, start = 1L)
age <- mature_age(matU, matR, start = 1L)
generation_time <- gen_time(matU, matR)
#mature_distrib(matU, start = 1L, c(FALSE, FALSE, FALSE, TRUE))

AgeReproTable <- data.frame(matrix(, ncol = 2, nrow = 3) )

AgeReproTable[1] <-  c("Prob of reaching mat", "Age at Mat", "Generation Time")
AgeReproTable[2] <- c(prob, age, generation_time)

knitr::kable(AgeReproTable, format = "latex", booktabs = TRUE)

```


