---
title: "Cephalopod Stage Matrix"
author: "Sophie Wulfing"
date: "12/15/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
setwd("C:/Users/sophi/Documents/UNH_Docs/Proposal")

library(matlib)
library(ggplot2)

observedStageMatrix <- as.matrix(data.frame(read.csv("RaberinaryBenbow2012Calcs.csv")))

```



```{r createMatrices}

myMats <- list()

for (i in 1:(nrow(observedStageMatrix)-5)){

  calcdStageMatrix <- matrix(, nrow = 4, ncol = 4)
  A <- observedStageMatrix[c(i:(i+3)), c(2:5)]
  
  for(j in 1:nrow(calcdStageMatrix)){
    
    b <-as.vector(observedStageMatrix[2:5, j + 1])
    X <- inv(A) %*% b
    
    calcdStageMatrix[j,] <- X#calcdStageMatrix[X,] <- vector
    
  }
  assign(paste0("calcdStageMatrix", i), calcdStageMatrix)
  myMats[i] <- mget(paste0("calcdStageMatrix", i))
}
```



```{r graphMatrices}
for (i in 1:length(myMats)){
  
  pop <- c(490, 976, 97, 12)
  N <- list()
 
  for (j in 1:6){
     N[[1]] <- pop
    N[[j+1]] <-myMats[[i]] %*% N[[j]]
 }

  modeled_data <- t(as.data.frame(do.call(cbind, N)))
  colnames(modeled_data) <- c("Stage_1", "Stage_2", "Stage_3", "Stage_4")
  modeled_data <- cbind(modeled_data, month = 0:6)

#write.csv(modeled_data, "testing.csv",row.names = TRUE)
  modeled_data <- data.frame(modeled_data)

print(ggplot(modeled_data) + 
  geom_line(aes(y = Stage_1, x = month, color = "Stage 1"), size = 1.5) + 
  geom_line(aes(y = Stage_2, x = month, color= "Stage 2"), size = 1.5) +
  geom_line(aes(y = Stage_3, x = month, color = "Stage 3"), size = 1.5) + 
  geom_line(aes(y = Stage_4, x = month, color= "Stage 4"), size = 1.5) +
  scale_color_manual(name = "", values = c("Stage 1" = "#009E73",
                                                "Stage 2" = "#F0E442",
                                                "Stage 3" = "#0072B2",
                                                "Stage 4" = "#D55E00")) +
  ggtitle(paste0("T = ", (i + 1), "-", (i + 4))) +
  xlab("Month") +
  ylab("No. Individuals"))
    
  }

```



```{r removeNegs}
myMatsZeros <- myMats
for(q in 1:length(myMatsZeros)){
  
  for(i in 1:nrow(myMatsZeros[[q]])){
  
  for( j in 1:ncol(myMatsZeros[[q]])){
    if(myMatsZeros[[q]][i,j] < 0) {
      myMatsZeros[[q]][i,j] <- 0
      
    }
  }
}
myMatsZeros
}

```



```{r graphWithZeros}
for (i in 1:length(myMatsZeros)){
  
  pop <- c(490, 976, 97, 12)
  N <- list()
 
  for (j in 1:6){
     N[[1]] <- pop
    N[[j+1]] <-myMatsZeros[[i]] %*% N[[j]]
 }

  modeled_data <- t(as.data.frame(do.call(cbind, N)))
  colnames(modeled_data) <- c("Stage_1", "Stage_2", "Stage_3", "Stage_4")
  modeled_data <- cbind(modeled_data, month = 0:6)

#write.csv(modeled_data, "testing.csv",row.names = TRUE)
  modeled_data <- data.frame(modeled_data)

print(ggplot(modeled_data) + 
  geom_line(aes(y = Stage_1, x = month, color = "Stage 1"), size = 1.5) + 
  geom_line(aes(y = Stage_2, x = month, color= "Stage 2"), size = 1.5) +
  geom_line(aes(y = Stage_3, x = month, color = "Stage 3"), size = 1.5) + 
  geom_line(aes(y = Stage_4, x = month, color= "Stage 4"), size = 1.5) +
  scale_color_manual(name = "", values = c("Stage 1" = "#009E73",
                                                "Stage 2" = "#F0E442",
                                                "Stage 3" = "#0072B2",
                                                "Stage 4" = "#D55E00")) +
  ggtitle(paste0("T = ", (i + 1), "-", (i + 4), ": negatives removed")) +
  xlab("Month") +
  ylab("No. Individuals"))
    
  }

```