---
title: "Wood's Quadratic Programming Method"
author: "Sophie Wulfing"
date: "2/17/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
setwd("C:/Users/sophi/Documents/GitHub/UNH_Docs/Proposal/Mtx_Model")

library(matlib)
library(ggplot2)
library(quadprog)
library(gridtext)
library(popbio)
library(tikzDevice)

observedData <- as.matrix(data.frame(read.csv("RaberinaryBenbow2012Calcs.csv")))
observedStageMatrix <- observedData[1:13, 2:5]
```

```{r matrix print,results = 'asis', echo = FALSE}
write_matex <- function(x) {
  begin <- "$$\\begin{bmatrix}"
  end <- "\\end{bmatrix}$$"
  X <-
    apply(x, 1, function(x) {
      paste(
        paste(x, collapse = "&"),
        "\\\\"
      )
    })
  writeLines(c(begin, X, end))
}
```

```{r initial things, echo = FALSE}
#Make Z
z <- matrix(t(observedStageMatrix[2:11,]), ncol = 1, nrow = 40, byrow = TRUE)
z

#Make M
m <- matrix(, nrow = nrow(z) , ncol = 8)
for(i in 1:(nrow(observedStageMatrix)-3)){
  m[(4 * (i-1) + 1):(4 * i),] <- matrix(c(observedStageMatrix[i,1], 0, 0, 0, 0, 0, observedStageMatrix[i,4], 0,
                                          0, observedStageMatrix[i,1], observedStageMatrix[i,2], 0, 0, 0, 0, 0,
                                          0, 0, 0, observedStageMatrix[i,2], observedStageMatrix[i,3], 0, 0, 0,
                                          0, 0, 0, 0, 0, observedStageMatrix[i,3], 0, observedStageMatrix[i,4]),
                                        nrow = 4, byrow = TRUE)
  #m
}

#Make C
c <- matrix(c(diag(8) * (-1), 
              1, 1, 0, 0, 0, 0, 0, 0,
              0, 0, 1, 1, 0, 0, 0, 0,
              0, 0, 0, 0, 1, 1, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 1), nrow = 12, ncol = 8, byrow = TRUE)
c
#Make b
b <- matrix(c(rep(0,8), rep(1,4)), nrow = 12, ncol = 1, byrow = TRUE)

#Make P
#p <- matrix(, nrow = 8, ncol = 1, byrow = TRUE) #vector(p1, g1, p2, g2, p3, g3, f4, p4)

#Make mtx G and vector x
g <- t(m) %*% m
f_t <- -(t(-z) %*% m)

qp <- solve.QP(Dmat = g, dvec = f_t, Amat = -t(c), bvec = -t(b))#, factorized = FALSE)


A <- matrix(c(qp$solution[1], 0, 0, qp$solution[7],
                 qp$solution[2], qp$solution[3], 0, 0,
                 0, qp$solution[4], qp$solution[5], 0,
                 0, 0, qp$solution[6], qp$solution[8]), byrow = TRUE, nrow = 4, ncol = 4)
A
```

```{r write A_generic, results = 'asis', echo = FALSE, fig.cap = "Matrix calculated using Wood's quadratic programming method"}

# subscripts <- c(gt_render("P1"['i']),  gt_render("F4"['i']),
#                 gt_render("G1"['i']), gt_render("P2"['i']),
#                  gt_render("G2"['i']), gt_render("P3"['i']),
#                 gt_render("G3"['i']), gt_render("P4"['i'])
#                 )
# 
# A_generic <- matrix(c(subscripts[1], 0, 0, subscripts[2],
#               subscripts[3], subscripts[4], 0, 0,
#               0, subscripts[5], subscripts[6], 0,
#               0, 0, subscripts[7], subscripts[8]), byrow = TRUE, nrow = 4, ncol = 4)

# 
# A_generic <- matrix(c(expression("P"[1]), 0, 0, expression("F"[4]),
#               expression("G"[1]), expression("P"[2]), 0, 0,
#               0, expression("G"[2]), expression("P"[3]), 0,
#               0, 0, expression("G"[3]), expression("P"[4])), byrow = TRUE, nrow = 4, ncol = 4)


A_generic <- matrix(c("$P_1$", 0, 0, "F4",
              "G1", "P2", 0, 0,
              0, "G2", "P3", 0,
              0, 0, "G3", "P4"), byrow = TRUE, nrow = 4, ncol = 4)

print(A_generic)
write_matex(A_generic)
```

```{r write A, results = 'asis', echo = FALSE, fig.cap = "Matrix calculated using Wood's quadratic programming method"}
write_matex(A)
```

```{r write A_rounded, results = 'asis', echo = FALSE, fig.cap = "Matrix calculated using Wood's quadratic programming method"}

A_round <- matrix( , byrow = TRUE, nrow = 4, ncol = 4)

for (i in 1:length(A)){
  A_round[i] <- round(A[i], 3)
}

# A_round <- matrix(-1*c(qp_round[1], 0, 0, qp_round[7],
#               qp_round[2], qp_round[3], 0, 0,
#               0, qp_round[4], qp_round[5], 0,
#               0, 0, qp_round[6], qp_round[8]), byrow = TRUE, nrow = 4, ncol = 4)

round_A <- matrix(A_round, 4, 4)

round_A[1] <- paste0("P1 = ", round_A[1])
round_A[13] <- paste0("F4 = ", round_A[13])
round_A[2] <- paste0("G1 = ", round_A[2])
round_A[6] <- paste0("P2 = ", round_A[6])
round_A[7] <- paste0("G2 = ", round_A[7])
round_A[11] <- paste0("P3 = ", round_A[11])
round_A[12] <- paste0("G3 = ", round_A[12])
round_A[16] <- paste0("P4 = ", round_A[16])


write_matex(round_A)
```

```{r projection, echo = FALSE}
pop <- observedStageMatrix[13,]
N <- list()


#72 mo projection
for (i in 1:120){
     N[[1]] <- pop
    N[[i+1]] <- A %*% N[[i]]
 }

modeled_data <- t(as.data.frame(do.call(cbind, N)))
colnames(modeled_data) <- c("Stage_1", "Stage_2", "Stage_3", "Stage_4")
modeled_data <- cbind(modeled_data, month = 0:120)

#write.csv(modeled_data, "testing.csv",row.names = TRUE)
modeled_data <- data.frame(modeled_data)

ggplot(modeled_data) + 
  geom_line(aes(y = Stage_1, x = month, color = "Stage 1"), size = 1.5) + 
  geom_line(aes(y = Stage_2, x = month, color= "Stage 2"), size = 1.5) +
  geom_line(aes(y = Stage_3, x = month, color = "Stage 3"), size = 1.5) + 
  geom_line(aes(y = Stage_4, x = month, color= "Stage 4"), size = 1.5) +
  scale_color_manual(name = "", values = c("Stage 1" = "#004949",
                                                "Stage 2" = "#009292",
                                                "Stage 3" = "#db6d00",
                                                "Stage 4" = "#920000")) +
  ggtitle("Ten year population projection") + #paste0(i, " month projection")) +
  xlab("Year") +
  ylab("No. Individuals") +
  scale_x_continuous(breaks = seq(0, 120, 12), label = seq(2006, 2016))

```

```{r A analysis}
#eigenvecors and vals
A_eigen <- eigen(A)
A_eigen

#Intrinsic Rate of Increast (r): lambda = e^r
r <- log(A_eigen$values[1])
r

#stable stage dist
A_stable_stage <- A_eigen$vectors[,1]/sum(A_eigen$vectors[,1]) 
A_stable_stage

#reproductive value
A_repro_value <- eigen(t(A))$vectors[,1]/eigen(t(A))$vectors[1,1]
A_repro_value

#mean reproductive value- is the avg no offspring?
A_repro_value %*% A_stable_stage

#. Vandermeer (1975, 1978)

#DO KEYFIT FUNCTION:
## Keyfitz function
keyfitz<-function(x,y){ # you provide the observed x
sum(abs(x-y))/2 # and stable stage dist vectors
} 
#SEE https://cws.auburn.edu/shared/files%3Fid=217&filename=ConMan_FileDownload_MatrixPopulation.pdf

#Good eigval and vector sources;
#https://setosa.io/ev/eigenvectors-and-eigenvalues/
#http://biom300.weebly.com/eigenvalues-and-eigenvectors-in-r.html
```

```{r lifeHistory, echo = FALSE}
pop <- c(1000, 0, 0, 0)
N <- list()


#72 mo projection
for (i in 1:240){
     N[[1]] <- pop
    N[[i+1]] <- A %*% N[[i]]
 }

modeled_data <- t(as.data.frame(do.call(cbind, N)))
colnames(modeled_data) <- c("Stage_1", "Stage_2", "Stage_3", "Stage_4")
modeled_data <- cbind(modeled_data, month = 0:240, pop = rowSums(modeled_data[,1:4]))


#write.csv(modeled_data, "testing.csv",row.names = TRUE)
modeled_data <- data.frame(modeled_data)

ggplot(modeled_data) + 
  geom_line(aes(y = pop, x = month), size = 1.5) + 
  ggtitle("Ten year population projection") + #paste0(i, " month projection")) +
  xlab("Year") +
  ylab("Total Pop") +
  geom_hline(yintercept=20, linetype="dashed", color = "red") +
  geom_hline(yintercept=20, linetype="dashed", color = "red") +
  scale_x_continuous(breaks = seq(0, 240, 24), label = seq(2006, 2016))

# ggplot(modeled_data[1:120,]) + 
#   geom_line(aes(y = Stage_1, x = month, color = "Stage 1"), size = 1.5) + 
#   geom_line(aes(y = Stage_2, x = month, color= "Stage 2"), size = 1.5) +
#   geom_line(aes(y = Stage_3, x = month, color = "Stage 3"), size = 1.5) + 
#   geom_line(aes(y = Stage_4, x = month, color= "Stage 4"), size = 1.5) +
#   scale_color_manual(name = "", values = c("Stage 1" = "#004949",
#                                                 "Stage 2" = "#009292",
#                                                 "Stage 3" = "#db6d00",
#                                                 "Stage 4" = "#920000")) +
#   ggtitle("Ten year population projection") + #paste0(i, " month projection")) +
#   xlab("Year") +
#   ylab("No. Individuals") +
#   scale_x_continuous(breaks = seq(0, 120, 12), label = seq(2006, 2016))

```

```{r sensElas, echo = FALSE}

cols <- hcl.colors(1000, palette = "Greens 3", alpha = NULL, rev = TRUE, fixup = TRUE)#, end = .85)

sens <- sensitivity(A)

for(i in 1:length(A)){
  if(A[i] == 0){
    sens[i] <-  NA
  }
}

## IMAGE plot with smaller boxes
image2(sens, mar=c(1,3.5,5,1), box.offset=.1, border="gray70",col = c("white", cols[150:850]), text.cex = 2)
 

## MATPLOT
matplot2(sens, log='y', type='b', yaxt='n', ltitle="Fate",
 ylab=expression(paste("Sensitivity of ",lambda)),
 main="Sensitivity matrix using matplot2")
pwrs <- -4:1
 #axis(2, 10^pwrs, parse(text=paste("10^", pwrs, sep = "")), las=1)



#https://rdrr.io/cran/popbio/man/sensitivity.html

#
```

```{r elasticity}

cols <- hcl.colors(1000, palette = "Greens 3", alpha = NULL, rev = TRUE, fixup = TRUE)#, end = .85)

elas <- elasticity(A)

for(i in 1:length(A)){
  if(A[i] == 0){
    elas[i] <-  NA
  }
}

image2(elas, mar=c(1,3.5,5,1), border="gray70", col = c("white", cols[150:850]), text.cex = 2 )

# # Summed elasticities for teasel.
# # fertility in last column, stasis P on diagonal, and growth in bottom-left triangle
# c(F=sum(elas[,4]), P=sum(diag(elas)), G=sum(elas[row(elas)>col(elas)]))
# 
# elas <- elasticity(tortoise[["med.high"]])
# image2(elas, mar=c(1,3.5,5,1),  log=FALSE)
#  title("Tortoise elasticity matrix", line=2.5)
# # Summed elasticities for tortoise (see example 9.4)
# # fertility in top row, stasis on diagonal, and growth on subdiagonal
# c(F=sum(elas[1,]), P=sum(diag(elas)), G=sum(elas[row(elas)==col(elas)+1]))

#https://rdrr.io/cran/popbio/man/elasticity.html
```
Possible Helpful Links:

https://stackoverflow.com/questions/12349122/solving-quadratic-programming-using-r

https://stackoverflow.com/questions/55727368/how-to-minimize-a-function-in-r-with-two-constraints

https://stackoverflow.com/questions/31301694/least-square-optimization-of-matrices-in-r?rq=1

https://henrywang.nl/quadratic-programming-with-r/

https://cran.r-project.org/web/packages/quadprog/quadprog.pdf

Also when you start doing this in markdown, here's the website for citations:
https://www.anthonyschmidt.co/post/2021-10-25-a-zotero-workflow-for-r/

