---
title: "Tidyverse Assignment"
author: "Sophie Wulfing"
date: "11/4/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(dplyr)
require(ggplot2)
require(knitr)

surveys <- read.csv("surveys.csv")
species <- read.csv("species.csv")
plots <- read.csv("plots.csv")

# Your goal is to create a R markdown document that does the following.
# 
# Using join functions to connect the different datasets into a single database
# Build a plot of weight versus hindfoot length, each species should be a different color
# Build a time series plot that shows the hindfoot length for each species during each month (so take the average within a month)
# Build a table that summarizes hindfoot length by species and sex (kable function in the knitr package is useful here)

```



```{r, echo=FALSE, warning = FALSE, message = FALSE}
# Using join functions to connect the different datasets into a single database
full_dataset <- inner_join(surveys, plots, row.names = FALSE)
full_dataset <- inner_join(full_dataset, species, row.names = FALSE)
full_dataset <- full_dataset[,c(1,2,3,4, 5, 10, 6, 13, 11, 12, 7, 9, 8)]
#write.csv(full_dataset, file = "full_dataset.csv", row.names = FALSE)

```



```{r, echo=FALSE, fig.cap = "Plot of weight versus hindfoot length, with each species as a different color", warning = FALSE, message = FALSE}
# Build a plot of weight versus hindfoot length, each species should be a different color
ggplot(data = full_dataset, aes(x = weight, y = hindfoot_length, color = species_id)) +
  geom_point() +
  theme(legend.position = "none") +
  xlab("Weight") + ylab("Hindfoot Length")
```



```{r, echo=FALSE, fig.cap = "Time Series plot of average monthly hindfoot length for each species", warning = FALSE, message = FALSE}
# Build a time series plot that shows the hindfoot length for each species during each month (so take the average within a month)
fulldata_timeSeries <- full_dataset %>% 
  group_by(year, month, species_id) %>%
  summarize(mean_len = mean(hindfoot_length))

fulldata_timeSeries$date <- as.Date(paste(fulldata_timeSeries$year, fulldata_timeSeries$month, "01", sep="-"), "%Y-%m-%d")

ggplot(data = fulldata_timeSeries, aes(x = date, y = mean_len, color = species_id)) +
  geom_point() +
  theme(legend.position = "none") +
  xlab("Date") + ylab("Mean Hindfoot Length")

```


\newpage



```{r, echo=FALSE, fig.cap = "Table summarizing hindfoot length by species and sex", warning = FALSE, message = FALSE}
# Build a table that summarizes hindfoot length by species and sex (kable function in the knitr package is useful here)

info_table <- full_dataset %>% 
  select(species, species_id, sex, hindfoot_length) %>%
  group_by(species, species_id, sex) %>% #Doesn't quite do anything yet, just secretly stores as different data sets.
  summarize(mean_len = mean(hindfoot_length), sd_len = sd(hindfoot_length)) %>% 
  filter(!is.na(mean_len))
kable(info_table, format = "markdown", col.names = c("Species", "Species ID", "Sex", "Mean Hindfoot Length", "Standard Deviation"), align = "l")

```
























