---
title: "Ch1 Figures"
author: "Sophie Wulfing"
date: '2022-08-04'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
setwd("C:/Users/sophi/Documents/UNH_Docs/Proposal/Mtx_Model")

library(matlib)
library(ggplot2)
library(quadprog)
library(gridtext)
library(popbio)
library(knitr)
library(gridExtra)
library(RColorBrewer) 
library(rPref)
library(dplyr)
library(ggpubr)

observedData <- as.matrix(data.frame(read.csv("RaberinaryBenbow2012Calcs.csv")))
observedStageMatrix <- observedData[1:13, 2:5]
```

```{r overallsurvive}
#Easton note: I am also including the larval survivability in this function. Should I not be doing that or should I create two that 
#Creat fxn to calculate matrices based on overall changes in survivability
survivability <- function(increase){
    #Calculate survivability for each staege and increase by x%
    NewMtx <- (A * increase) + A
    
    for(i in 1:ncol(NewMtx)-1){
      if(sum(NewMtx[,i]) > 1 | NewMtx[4,4] > 1){
        return(NA)
      }
      else{return(NewMtx)}
    }
}


#This is stupid but it just forces R to stop writing things as complex numbers
f <- function(x) {
   if (all(Im(z <- zapsmall(x))==0)) as.numeric(z) else x
}

real_check <- function(mtx){
  if(sum(mtx[,1]) > 1 | sum(mtx[,2]) > 1 | sum(mtx[,3]) > 1 | mtx[4,4] > 1){
    return(NA)
  }
  else{return(mtx)}
}

```

```{r matrix print,results = 'asis', echo = FALSE}
write_matex <- function(x) {
  begin <- "$$\\begin{bmatrix}"
  end <- "\\end{bmatrix}$$"
  X <-
    apply(x, 1, function(x) {
      paste(
        paste(x, collapse = "&"),
        "\\\\"
      )
    })
  writeLines(c(begin, X, end))
}

```


```{r initial things, echo = FALSE}
#Make Z
z <- matrix(t(observedStageMatrix[2:11,]), ncol = 1, nrow = 40, byrow = TRUE)
z

#Make M
m <- matrix(, nrow = nrow(z) , ncol = 8)
for(i in 1:(nrow(observedStageMatrix)-3)){
  m[(4 * (i-1) + 1):(4 * i),] <- matrix(c(observedStageMatrix[i,1], 0, 0, 0, 0, 0, observedStageMatrix[i,4], 0,
                                          0, observedStageMatrix[i,1], observedStageMatrix[i,2], 0, 0, 0, 0, 0,
                                          0, 0, 0, observedStageMatrix[i,2], observedStageMatrix[i,3], 0, 0, 0,
                                          0, 0, 0, 0, 0, observedStageMatrix[i,3], 0, observedStageMatrix[i,4]),
                                        nrow = 4, byrow = TRUE)
  #m
}

#Make C
c <- matrix(c(diag(8) * (-1), 
              1, 1, 0, 0, 0, 0, 0, 0,
              0, 0, 1, 1, 0, 0, 0, 0,
              0, 0, 0, 0, 1, 1, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 1), nrow = 12, ncol = 8, byrow = TRUE)
c
#Make b
b <- matrix(c(rep(0,8), rep(1,4)), nrow = 12, ncol = 1, byrow = TRUE)

#Make P
#p <- matrix(, nrow = 8, ncol = 1, byrow = TRUE) #vector(p1, g1, p2, g2, p3, g3, f4, p4)

#Make mtx G and vector x
g <- t(m) %*% m
f_t <- -(t(-z) %*% m)

qp <- solve.QP(Dmat = g, dvec = f_t, Amat = -t(c), bvec = -t(b))#, factorized = FALSE)


A <- matrix(c(qp$solution[1], 0, 0, qp$solution[7],
                 qp$solution[2], qp$solution[3], 0, 0,
                 0, qp$solution[4], qp$solution[5], 0,
                 0, 0, qp$solution[6], qp$solution[8]), byrow = TRUE, nrow = 4, ncol = 4)
A
```

```{r write A, results = 'asis', echo = FALSE, fig.cap = "Matrix calculated using Wood's quadratic programming method"}
write_matex(A)
```

```{r projection, echo = FALSE}
pop <- observedStageMatrix[13,]
N <- list()


#72 mo projection
for (i in 1:120){
     N[[1]] <- pop
    N[[i+1]] <- A %*% N[[i]]
 }

modeled_data <- t(as.data.frame(do.call(cbind, N)))
colnames(modeled_data) <- c("Stage_1", "Stage_2", "Stage_3", "Stage_4")
modeled_data <- cbind(modeled_data, month = 0:120)

#write.csv(modeled_data, "testing.csv",row.names = TRUE)
modeled_data <- data.frame(modeled_data)

ggplot(modeled_data) + 
  geom_line(aes(y = Stage_1, x = month, color = "Stage 1"), size = 1.5) + 
  geom_line(aes(y = Stage_2, x = month, color= "Stage 2"), size = 1.5) +
  geom_line(aes(y = Stage_3, x = month, color = "Stage 3"), size = 1.5) + 
  geom_line(aes(y = Stage_4, x = month, color= "Stage 4"), size = 1.5) +
  scale_color_manual(name = "", values = c("Stage 1" = "#004949",
                                                "Stage 2" = "#009292",
                                                "Stage 3" = "#db6d00",
                                                "Stage 4" = "#920000")) +
  ggtitle("Ten year population projection") + #paste0(i, " month projection")) +
  xlab("Year") +
  ylab("No. Individuals") +
  scale_x_continuous(breaks = seq(0, 120, 12), label = seq(2006, 2016))

```

```{r A analysis}
#eigenvecors and vals
A_eigen <- eigen(A)
A_eigen

#Intrinsic Rate of Increast (r): lambda = e^r
r <- log(A_eigen$values[1])
r

#stable stage dist
A_stable_stage <- A_eigen$vectors[,1]/sum(A_eigen$vectors[,1]) 
A_stable_stage

#reproductive value
A_repro_value <- eigen(t(A))$vectors[,1]/eigen(t(A))$vectors[1,1]
A_repro_value

#mean reproductive value- is the avg no offspring?
A_repro_value %*% A_stable_stage

#. Vandermeer (1975, 1978)

#DO KEYFIT FUNCTION:
## Keyfitz function
keyfitz<-function(x,y){ # you provide the observed x
sum(abs(x-y))/2 # and stable stage dist vectors
} 
#SEE https://cws.auburn.edu/shared/files%3Fid=217&filename=ConMan_FileDownload_MatrixPopulation.pdf

#Good eigval and vector sources;
#https://setosa.io/ev/eigenvectors-and-eigenvalues/
#http://biom300.weebly.com/eigenvalues-and-eigenvectors-in-r.html
```

```{r sensElas, echo = FALSE}

cols <- hcl.colors(1000, palette = "Greens 3", alpha = NULL, rev = TRUE, fixup = TRUE)#, end = .85)

sens <- sensitivity(A)

for(i in 1:length(A)){
  if(A[i] == 0){
    sens[i] <-  NA
  }
}

## IMAGE plot with smaller boxes
image2(sens, mar=c(1,3.5,5,1), box.offset=.1, border="gray70",col = c("white", cols[150:850]), text.cex = 2)
 

## MATPLOT
matplot2(sens, log='y', type='b', yaxt='n', ltitle="Fate",
 ylab=expression(paste("Sensitivity of ",lambda)),
 main="Sensitivity matrix using matplot2")
pwrs <- -4:1
 #axis(2, 10^pwrs, parse(text=paste("10^", pwrs, sep = "")), las=1)



#https://rdrr.io/cran/popbio/man/sensitivity.html

#
```

```{r elasticity}

cols <- hcl.colors(1000, palette = "Greens 3", alpha = NULL, rev = TRUE, fixup = TRUE)#, end = .85)

elas <- elasticity(A)

for(i in 1:length(A)){
  if(A[i] == 0){
    elas[i] <-  NA
  }
}

image2(elas, mar=c(1,3.5,5,1), border="gray70", col = c("white", cols[150:850]), text.cex = 2 )

# # Summed elasticities for teasel.
# # fertility in last column, stasis P on diagonal, and growth in bottom-left triangle
# c(F=sum(elas[,4]), P=sum(diag(elas)), G=sum(elas[row(elas)>col(elas)]))
# 
# elas <- elasticity(tortoise[["med.high"]])
# image2(elas, mar=c(1,3.5,5,1),  log=FALSE)
#  title("Tortoise elasticity matrix", line=2.5)
# # Summed elasticities for tortoise (see example 9.4)
# # fertility in top row, stasis on diagonal, and growth on subdiagonal
# c(F=sum(elas[1,]), P=sum(diag(elas)), G=sum(elas[row(elas)==col(elas)+1]))

#https://rdrr.io/cran/popbio/man/elasticity.html
```

```{r iteration}
#Calculates new rates based on vectors of % chagne and frequencies of restrictions
percentage <-rates <- c(seq(0, 1, .01)) # c(0.01, 0.05, 0.1, 0.15) 
freqs <- c(seq(1, 12)) #c(1, 2, 3, 4, 6, 12) 
iteration <- data.frame(matrix(ncol=4,nrow=0, dimnames=list(NULL, c("Frequency", "PercentChange", "mu", "lambda"))))

for(i in 1:length(freqs)){
  for(j in 1:length(percentage)){
    if (!is.na(real_check(survivability(percentage[j])))){
      mu <- ((freqs[i]-1) * log(eigen(A)$values[1]) + log(eigen(survivability(percentage[j]))$values[1]))/ freqs[i]
      lambda <- exp(mu)
          iteration[nrow(iteration) + 1,] <- c(freqs[i], percentage[j], f(mu), f(lambda))
    }
      # neweig <- (eigen(survivability(percentage[j]))$values[1] + (freqs[i]-1) * eigen(A)$values[1]) / freqs[i]
  }
}
#kable(iteration)
 
# Sources: https://www.webpages.uidaho.edu/wlf448/stochgro.pdf
# https://esajournals.onlinelibrary.wiley.com/doi/10.2307/1943004
```

```{r idkrandom}


#Continuous Colors
ggplot(iteration, aes(Frequency, PercentChange, fill = lambda)) + geom_tile(width=1) +
  scale_fill_gradient2(
  low = "red",
  mid = "white",
  high = "green",
  #limits = c(1, max(iteration$lambda)),
  midpoint = 1,
  space = "Lab",
  na.value = "grey50") +
  scale_x_continuous(name = "Frequency of closure (months)", expand=c(0,0), breaks = c(1, 3, 6, 9, 12)) +
  scale_y_continuous(name = "Percent change in survival", expand=c(0,0)) +
  labs(fill = "Eigenvalue")

```

```{r paretto}

#DO I NEED THIS
# moopshoop <- function(rate, freq){
#   mu <- ((freq-1) * log(eigen(A)$values[1]) + log(eigen(survivability(rate))$values[1]))/ freq
#   lambda <- exp(mu)
#   return(f(lambda))
# }

#Paretto fromt LOOK UP ITS WHAT THIS IS TELLING YOU. look in optimization lit
#see:https://www.pnas.org/doi/full/10.1073/pnas.1911440116

#https://www.rdocumentation.org/packages/GPareto/versions/1.1.6/topics/easyGParetoptim

#https://rdrr.io/cran/rPref/man/plot_front.html
# plots Pareto fronts for the hp/mpg values of mtcars

paretospagheto <- iteration %>% filter(lambda >= 1)

show_front <- function(pref) {
  plot(paretospagheto$Frequency, paretospagheto$PercentChange)
  sky <- psel(paretospagheto, pref)
  plot_front(paretospagheto, pref, col = rgb(0, 0, 1))
  points(sky$Frequency, sky$PercentChange, lwd = 3)
}

# do this for all four combinations of Pareto compositions
#show_front(low(Frequency)  * low(PercentChange))
#show_front(low(Frequency)  * high(PercentChange))
show_front(high(Frequency) * low(PercentChange)) #This is the optimal scenario
#show_front(high(Frequency) * high(PercentChange))

# compare this to the front of a intersection preference
show_front(high(Frequency) | low(PercentChange))
```
