---
title: "CalcsTest"
author: "Sophie Wulfing"
date: "2023-01-16"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = TRUE)
setwd("C:/Users/sophi/Documents/GitHub/UNH_Docs/Proposal/Mtx_Model")

library(knitr)
library(matlib)
library(ggplot2)
library(quadprog)
library(gridtext)
library(popbio)
library(gridExtra)
library(RColorBrewer) 
library(rPref)
library(tidyr)
library(dplyr)
library(ggpubr)
library(KraljicMatrix)

observedData <- as.matrix(data.frame(read.csv("RaberinaryBenbow2012Calcs.csv")))
observedStageMatrix <- observedData[1:13, 2:5]

```

```{r initial things}
#Make Z
z <- matrix(t(observedStageMatrix[2:11,]), ncol = 1, nrow = 40, byrow = TRUE)
#z

#Make M
m <- matrix(, nrow = nrow(z) , ncol = 8)
for(i in 1:(nrow(observedStageMatrix)-3)){
  m[(4 * (i-1) + 1):(4 * i),] <- matrix(c(observedStageMatrix[i,1], 0, 0, 0, 0, 0, observedStageMatrix[i,4], 0,
                                          0, observedStageMatrix[i,1], observedStageMatrix[i,2], 0, 0, 0, 0, 0,
                                          0, 0, 0, observedStageMatrix[i,2], observedStageMatrix[i,3], 0, 0, 0,
                                          0, 0, 0, 0, 0, observedStageMatrix[i,3], 0, observedStageMatrix[i,4]),
                                        nrow = 4, byrow = TRUE)
  #m
}

#Make C
c <- matrix(c(diag(8) * (-1), 
              1, 1, 0, 0, 0, 0, 0, 0,
              0, 0, 1, 1, 0, 0, 0, 0,
              0, 0, 0, 0, 1, 1, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 1), nrow = 12, ncol = 8, byrow = TRUE)
#c
#Make b
b <- matrix(c(rep(0,8), rep(1,4)), nrow = 12, ncol = 1, byrow = TRUE)

#Make P
#p <- matrix(, nrow = 8, ncol = 1, byrow = TRUE) #vector(p1, g1, p2, g2, p3, g3, f4, p4)

#Make mtx G and vector x
g <- t(m) %*% m
f_t <- -(t(-z) %*% m)

qp <- solve.QP(Dmat = g, dvec = f_t, Amat = -t(c), bvec = -t(b))#, factorized = FALSE)


A <- matrix(c(qp$solution[1], 0, 0, qp$solution[7],
                 qp$solution[2], qp$solution[3], 0, 0,
                 0, qp$solution[4], qp$solution[5], 0,
                 0, 0, qp$solution[6], qp$solution[8]), byrow = TRUE, nrow = 4, ncol = 4)
#A
```

```{r overallsurvive}
#Easton note: I am also including the larval survivability in this function. Should I not be doing that or should I create two that 
#Creat fxn to calculate matrices based on overall changes in survivability
survivability <- function(increase){
    #Calculate survivability for each staege and increase by x%
    NewMtx <- (A * increase) + A
    
    for(i in 1:ncol(NewMtx)-1){
      if(sum(NewMtx[,i]) > 1 | NewMtx[4,4] > 1){
        return(NA)
      }}
    return(NewMtx)
}


#This is stupid but it just forces R to stop writing things as complex numbers
f <- function(x) {
   if (all(Im(z <- zapsmall(x))==0)) as.numeric(z) else x
}

real_check <- function(mtx){
  if(sum(mtx[,1]) > 1 | sum(mtx[,2]) > 1 | sum(mtx[,3]) > 1 | mtx[4,4] > 1){
    return(NA)
  }
  else{return(mtx)}
}

```

```{r iteration}
#Calculates new rates based on vectors of % chagne and frequencies of restrictions
percentage <-rates <- c(seq(0, 1, .01)) # c(0.01, 0.05, 0.1, 0.15)
freqs <- c(seq(1, 12)) #c(1, 2, 3, 4, 6, 12)
iteration <- data.frame(matrix(ncol=4,nrow=0, dimnames=list(NULL, c("Frequency", "PercentChange", "mu", "lambda"))))

for(i in 1:length(freqs)){
  for(j in 1:length(percentage)){
    if (!is.na(survivability(percentage[j]))){
      mu <- ((freqs[i]-1) * log(eigen(A)$values[1]) + log(eigen(survivability(percentage[j]))$values[1]))/ freqs[i]
      lambda <- exp(mu)
          iteration[nrow(iteration) + 1,] <- c(freqs[i], percentage[j], f(mu), f(lambda))
    }
      # neweig <- (eigen(survivability(percentage[j]))$values[1] + (freqs[i]-1) * eigen(A)$values[1]) / freqs[i]
  }
}
#kable(iteration)

# Sources: https://www.webpages.uidaho.edu/wlf448/stochgro.pdf
# https://esajournals.onlinelibrary.wiley.com/doi/10.2307/1943004
```

```{r projectionsNewCalc, fig.cap = "Projections based on multiplying matrices"}

####Note, this is calculated differently than the idk random block as this was calculated by multiplying the matrices, not the eigenvalues
p <- list()
modeled_data <- data.frame(matrix(ncol=8,nrow=0, dimnames=list(NULL, c("Stage_1", "Stage_2", "Stage_3", "Stage_4", "month", "pop", "Frequency", "PercentChange"))))
percentage <-rates <- c(seq(0, .1, .01)) # c(0.01, 0.05, 0.1, 0.15) 
freqs <- c(seq(1, 12)) #c(1, 2, 3, 4, 6, 12) 
#par(mfrow = c(6,4))
for(i in 1:length(freqs)){
  for(j in 1:length(percentage)){
    pop <- observedStageMatrix[13,]
    N <- list()
    for (k in 1:120){
      if(k %% freqs[i] == 0){
        N[[1]] <- pop
        N[[k+1]] <- survivability(percentage[j]) %*% N[[k]]
        }
      else{
        N[[1]] <- pop
        N[[k+1]] <- A %*% N[[k]]
      }}
   
  
  new_data <- t(as.data.frame(do.call(cbind, N)))
  colnames(new_data) <- c("Stage_1", "Stage_2", "Stage_3", "Stage_4")
  new_data <- data.frame(cbind(new_data, month = 0:120, pop = rowSums(new_data[,1:4]), Frequency = freqs[i], PercentChange = percentage[j]))
  modeled_data <- rbind(modeled_data, new_data)
  }} 

#### CALCULATE GROWTH RATE BASED ON LAST POP-FIRST POP/FIRST POP FOR EACH FREQ/PERCENT COMBINATION
growthRate <- modeled_data %>%
  select(month, pop, Frequency, PercentChange) %>%
  filter(month == 0 | month == 120) %>%
  pivot_wider(names_from = month, values_from = pop) %>%
  rename(month_0 = 3,
         month_120 = 4) %>%
  mutate(Mu_New = log(month_120/month_0)/120) %>% #See Crouse paper. From Nt = N0e^(rt)
  mutate(lambda_new = exp(Mu_New)) %>%
  select(Frequency, PercentChange, Mu_New, lambda_new)

  

#### COPY PARETTO GRAPH FROM OTHER ANALYSIS
paretospagheto <- growthRate %>% 
  filter(lambda_new >= 1) %>%
  group_by(Frequency) %>%
  filter(lambda_new == min(lambda_new))

paretospagheto$Frequency <- paretospagheto$Frequency - 0.5
paretospagheto$PercentChange <- paretospagheto$PercentChange - 0.005


#Continuous Colors
ggplot(growthRate, aes(Frequency, PercentChange, fill = lambda_new)) + geom_tile(width=1) +
  scale_fill_gradient2(
  low = "red",
  mid = "white",
  high = "green",
  #limits = c(1, max(growthRate$lambda_new)),
  midpoint = 1,
  space = "Lab",
  na.value = "grey50") +
  scale_x_continuous(name = "Frequency of closure (months)", expand=c(0,0), breaks = c(1, 3, 6, 9, 12)) +
  scale_y_continuous(name = "Percent change in survival", expand=c(0,0)) +
  labs(fill = "Eigenvalue") +
  geom_segment(aes(x = 5.5, y = .095, xend = 5.5, yend = 0.105), size = .5, color = "#5A5A5A") +
    geom_segment(aes(x = 4.5, y = .095, xend = 5.5, yend = 0.095), size = .5, color = "#5A5A5A") +
  geom_step(data = paretospagheto , aes(x=Frequency, y=PercentChange), size = .5, color = "#5A5A5A") 


#####PLOTTING ALL RATES
#   #write.csv(modeled_data, "testing.csv",row.names = TRUE)
# 
#   #plot(modeled_data$pop, type = "o")  
# ggplot(modeled_data, aes(y = pop, x = month)) +
#   geom_line(size = 1.5) +
#   #ggtitle()+#paste0("Surv rate: ", iteration[i,2], " Freq: Close once every ", iteration[i,1], " months" )) + #paste0(i, " month projection")) +
#   xlab("Year") +
#   ylab("Total Pop") +
#   ylim(0,1000) +
#   scale_x_continuous(breaks = seq(0, 120, 120), label = c(2006, 2016)) +
#   facet_grid(Frequency ~ PercentChange)

```

```{r idkrandom, fig.cap = "Projections based on multiplying eigenvalues"}
mycolors <- colorRampPalette(brewer.pal(9, "RdYlBu"))(1177)

iteration_popDy <- iteration %>%
  mutate(PopDynamics = case_when(
    lambda < 1 ~ "Negative",
    lambda >= 1 ~ "Positive"
  ))

iteration_bins <- iteration %>%
  mutate(PopDynamics = case_when(
    lambda < 1 ~ "Decrease",
    lambda >= 1 & lambda < 1.25 ~ "0-25",
    lambda >= 1.25 & lambda < 1.5 ~ "25-50",
    lambda >= 1.5 & lambda < 1.75 ~ "50-75",
    lambda >= 1.75 & lambda < 2 ~ "75-100"
  ))

# #Discrete Colors
# ggplot(iteration_popDy, aes(Frequency, PercentChange, fill = PopDynamics)) + geom_tile(width=1) +
#   scale_fill_manual(
#   values = c("red", "green")
# )

#Pareto
paretospagheto <- iteration %>% 
  filter(lambda >= 1) %>%
  group_by(Frequency) %>%
  filter(lambda == min(lambda))

paretospagheto$Frequency <- paretospagheto$Frequency - 0.5
paretospagheto$PercentChange <- paretospagheto$PercentChange - 0.005


#Continuous Colors
ggplot(iteration, aes(Frequency, PercentChange, fill = lambda)) + geom_tile(width=1) +
  scale_fill_gradient2(
  low = "red",
  mid = "white",
  high = "green",
  #limits = c(1, max(iteration$lambda)),
  midpoint = 1,
  space = "Lab",
  na.value = "grey50") +
  scale_x_continuous(name = "Frequency of closure (months)", expand=c(0,0), breaks = c(1, 3, 6, 9, 12)) +
  scale_y_continuous(name = "Percent change in survival", expand=c(0,0)) +
  labs(fill = "Eigenvalue") +
  geom_segment(aes(x = 5.5, y = .095, xend = 5.5, yend = 0.105), size = .5, color = "#5A5A5A") +
    geom_segment(aes(x = 4.5, y = .095, xend = 5.5, yend = 0.095), size = .5, color = "#5A5A5A") +
  geom_step(data = paretospagheto , aes(x=Frequency, y=PercentChange), size = .5, color = "#5A5A5A")



#https://ggplot2.tidyverse.org/reference/scale_gradient.html

#Okay so I changed what this is showing because it became kind of redundant with the other graph. This now bins it into amounts of pop increase

```

```{r percentDiff, fig.cap = "Histogram of the percent differences between the two calculations with the highest percent difference being 0.063%"}
comparison <- left_join(iteration, growthRate, by=c("Frequency", "PercentChange")) %>%
  mutate(percentDifference = (lambda_new-lambda)/lambda) 

comparison$dynamicChange <- NA

#Checking to see if any rows have different overall dynamics (one says increasing while the other is decreasing)
for(i in 1:nrow(comparison)){
  if(comparison$mu[i] > 0 & comparison$Mu_New[i] > 0){
    comparison$dynamicChange[i] <- FALSE
  }
  else if(comparison$mu[i] < 0 & comparison$Mu_New[i] < 0){
    comparison$dynamicChange[i] <- FALSE
  }
  else if(comparison$mu[i] == 0 & comparison$Mu_New[i] == 0){
    comparison$dynamicChange[i] <- FALSE
  }
  else{
    comparison$dynamicChange[i] <- TRUE
  }
}
  
 
justtobesure <- comparison %>%
  filter(dynamicChange == TRUE)
 
hist(comparison$percentDifference)
  
  
  
  
  
  
  
  

```
Note: I also checked if any of the percent differences were enough to change the overall pop dynamics (like change it from increasing in one calculation to decreasing in the other) and all kept the same overall trends.

```{r threeMoClosures}

p <- list()
modeled_data <- data.frame(matrix(ncol=7,nrow=0, dimnames=list(NULL, c("Stage_1", "Stage_2", "Stage_3", "Stage_4", "month", "pop", "PercentChange"))))
#par(mfrow = c(6,4))


for(i in 1:length(percentage)){ 
  pop <- observedStageMatrix[13,]
  N <- list()
  for (j in 1:120){
    if(j %% 12 %in% c(1,2,3)){
      N[[1]] <- pop
      N[[j+1]] <- survivability(percentage[i]) %*% N[[j]]
      }
    else{
       N[[1]] <- pop
      N[[j+1]] <- A %*% N[[j]]
    }}
   
  
  new_data <- t(as.data.frame(do.call(cbind, N)))
  colnames(new_data) <- c("Stage_1", "Stage_2", "Stage_3", "Stage_4")
  new_data <- data.frame(cbind(new_data, month = 0:120, pop = rowSums(new_data[,1:4]), PercentChange = percentage[i]))
  modeled_data <- rbind(modeled_data, new_data)
  
} 

#### CALCULATE GROWTH RATE BASED ON LAST POP-FIRST POP/FIRST POP FOR EACH FREQ/PERCENT COMBINATION
growthRate <- modeled_data %>%
  select(month, pop, PercentChange) %>%
  filter(month == 0 | month == 120) %>%
  pivot_wider(names_from = month, values_from = pop) %>%
  rename(month_0 = 2,
         month_120 = 3) %>%
  mutate(Mu_New = log(month_120/month_0)/120) %>% #See Crouse paper. From Nt = N0e^(rt)
  mutate(lambda_new = exp(Mu_New)) %>%
  select(PercentChange, Mu_New, lambda_new)


trend <- lm(growthRate$Mu_New ~ growthRate$PercentChange)
xint <- -coef(trend)[1]/coef(trend)[2]


plot(growthRate$PercentChange, growthRate$Mu_New, xlab = "Change in survival rate as a result of closure", ylab = "Population growth rate")
abline(trend)
abline(h = 0, col = "red")
text(0.02, 0.005, paste0("X intercept = ", xint))


```