---
title: "Wulfing_HW08"
author: "Sophie Wulfing"
date: '2022-04-04'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(R2jags)
library(tidyr)
library(dplyr)

setwd("~/UNH_Docs/NR913")

cephs <- read.csv("C:/Users/sophi/Documents/UNH_Docs/Proposal/CNH2_data/cleanData.csv")

site_data <- cephs %>%
    group_by(REGION) %>%
    summarise(Count = n()) %>%
    filter(Count > 150)

ceph_sites <- cephs %>%
  filter(REGION %in% site_data$REGION)

ceph_sites2 <- transform(ceph_sites,id=as.numeric(factor(REGION)))

ceph_model <- transform(cephs,id=as.numeric(factor(REGION)), sex_id=(as.numeric(factor(FISHER_SEX))-1))
ceph_sex <- ceph_model %>% drop_na(sex_id)
```

```{r sitewt, echo = FALSE}

#Questions about this one: can you do a p val for an anova? Does the calc look the same?
#wANT TO REMAKE data next

#ANOVA
#Only looking at most fished sites
#Different variances?

#Visualize Data-FIX THIS
boxplot(as.numeric(AVG_WT) ~ REGION, 
        ylab = "Average wt of Cepalopod",
        xlab = "Site",
        # outline = TRUE,
        # notch = FALSE,
        # staplewex = 0.2,
        # boxwex = 0.4,
        # border = TRUE,
        data = ceph_sites2)

sink("cephs_sitewt.txt")
cat(" 
    model {
    
    # PRIORS
    for(i in 1:nsites){       #loop for alphas. can also do alpha[1] alpha[2]
    alpha[i] ~ dnorm(0,0.001)
    }
    tau <- 1/sigma^2
    sigma ~ dunif(0,100) #This gives only 1 variance across all sites
    
    # LIKELIHOOD
    for(i in 1:n){
    mass[i] ~ dnorm(mu[i],tau)
    mu[i] <- alpha[site[i]] #Mean will vary by site. 3 alphas, 1 per site. loop through every row of your dataset.
    } # i
    
    # # derived quantitites
    # diff23 <- alpha[3] - alpha[2]

    # # generate new data from the fitted model
    # for(i in 1:n){
    # y.new[i] ~ dnorm(mu[i],tau)   #Generates new data for each run of mcmc
    #  }
    
    } # end of model  
    ",fill = TRUE)
sink()

win.data <- list(mass   = ceph_sites2$AVG_WT,
                 site   = ceph_sites2$id, 
                 n      = nrow(ceph_sites2),
                 nsites = length(unique(ceph_sites2$id)))

# Initial values
inits <- function()list(alpha = rnorm(7), sigma = rlnorm(1))

# Parameters monitored
params <- c("alpha",
            "sigma"
            #"Bayes.P"
            #"y.new"
) 

# MCMC settings
ni <- 1000; nt <- 3; nb <- 100; nc <- 3


out_stwt <- jags(win.data, inits, params, "cephs_sitewt.txt", 
            n.chains = nc, n.thin = nt, n.iter = ni, n.burnin = nb, 
            working.directory = getwd())
print(out_stwt, dig = 1) 


```

```{r siteno, echo = FALSE}

 #ANOVA
#Visualize Data
#Pval and regenerate data
#CHANGE TO POISSON?
#Different variances?

boxplot(NO_CAUGHT ~ REGION, 
        ylab = "No per catch",
        xlab = "Site",
        outline = TRUE,
        notch = FALSE,
        staplewex = 0.2,
        boxwex = 0.4,
        border = TRUE,
        data = ceph_sites2)

sink("cephs_siteno.txt")
cat(" 
    model {
    
    # PRIORS
    for(i in 1:nsites){       #loop for alphas. can also do alpha[1] alpha[2]
    alpha[i] ~ dnorm(0,0.001)
    }
    tau <- 1/sigma^2
    sigma ~ dunif(0,100) #This gives only 1 variance across all sites
    
    # LIKELIHOOD
    for(i in 1:n){
    mass[i] ~ dnorm(mu[i],tau)
    mu[i] <- alpha[site[i]] #Mean will vary by site. 3 alphas, 1 per site. loop through every row of your dataset.
    } # i
    
    # # derived quantitites
    # diff23 <- alpha[3] - alpha[2]

    # # generate new data from the fitted model
    # for(i in 1:n){
    # y.new[i] ~ dnorm(mu[i],tau)   #Generates new data for each run of mcmc
    #  }
    
    } # end of model  
    ",fill = TRUE)
sink()

win.data <- list(mass   = ceph_sites2$NO_CAUGHT,
                 site   = ceph_sites2$id, 
                 n      = nrow(ceph_sites2),
                 nsites = length(unique(ceph_sites2$id)))

# Initial values
inits <- function()list(alpha = rnorm(7), sigma = rlnorm(1))

# Parameters monitored
params <- c("alpha",
            "sigma"
            #"Bayes.P"
            #"y.new"
) 

# MCMC settings
ni <- 1000; nt <- 3; nb <- 100; nc <- 3


out_stno <- jags(win.data, inits, params, "cephs_siteno.txt", 
                 n.chains = nc, n.thin = nt, n.iter = ni, n.burnin = nb, 
                 working.directory = getwd())
print(out_stno, dig = 1) 

```

```{r sexno, echo = FALSE}
#TTEST
#Fix out plots then idk lol

poisson.t.test <- glm(ceph_model$NO_CAUGHT ~ ceph_model$sex_id, family = poisson)
summary(poisson.t.test) #effect of arable are significant. ESTIMATES ARE ON LOG SCALE

#Visualize Data-FIX THIS
boxplot(NO_CAUGHT ~ FISHER_SEX, 
        ylab = "No caught per landing",
        xlab = "Site",
        outline = TRUE,
        notch = FALSE,
        staplewex = 0.2,
        boxwex = 0.4,
        border = TRUE,
        data = ceph_model)

sink("cephs_sexno.txt")
cat(" 
    model {
    
    # PRIORS
    beta0 ~ dnorm(0,0.001)  # intercept
    beta1 ~ dnorm(0,0.001)  # effect of M/F, IDK
    
    # LIKELIHOOD
    for(i in 1:n){
    cephs[i] ~ dpois(lambda[i]) #error term built in bc lambda is both mean and var
    log(lambda[i]) <- beta0 + beta1 * sex[i] # sex needs to be 0s and 1s. predicting log of lambda, not lambda
    #lambda[i] <- exp(beta0 + beta1 * sex[i] ) Alternative form
    
    
    # CHECK MODEL FIT
    presid[i] <- (cephs[i] - lambda[i])/sqrt(lambda[i])          # Pearson residual- corrects for larger mean => larger var
    cephs.new[i] ~ dpois(lambda[i])                              # new data from fitted model
    presid.new[i] <- (cephs.new[i] - lambda[i])/sqrt(lambda[i])  # Pearson residual for new data

    D[i] <- presid[i]^2          # squared Pearson residuals for observed data
    D.new[i] <- presid.new[i]^2  # squared Pearson residuals for new data
    
    
    } # i
    

    # CHECK MODEL FIT - BAYESIAN P-VALUE
    D.sum <- sum(D[])                      # sum of squared residuals for raw data
    D.new.sum <- sum(D.new[])              # same, but for model-generated data
    Bayes.P <- step(D.new.sum/D.sum - 1)   # step(x) tests if x >= 0
    
    } # end of model  
    ",fill = TRUE)
sink()

win.data <- list(cephs = as.integer(ceph_sex$NO_CAUGHT), 
                 sex  = ceph_sex$sex_id,
                 n  = nrow(ceph_sex))

# Initial values
inits <- function()list(beta0  = rnorm(1),
                        beta1  = rnorm(1))

# Parameters monitored
params <- c("beta0",
            "beta1",
            "Bayes.P",
            "D.sum",
            "D.new.sum",
            "cephs.new")

# MCMC settings
ni <- 3000; nt <- 1; nb <- 1000; nc <- 3

out_sexno <- jags(win.data, inits, params, "cephs_sexno.txt", 
                  n.chains = nc, n.thin = nt, n.iter = ni, n.burnin = nb, 
                  working.directory = getwd())
print(out_sexno, dig = 2)

# plot parameter posteriors
o <- out_sexno$BUGSoutput$sims.list

d <- density(o$beta0)
d2 <- density(o$beta1)

plot(d,
     xlab = "Posterior distribution",
     ylim = c(0,3),
     xlim = c(-1,1.5),
     main = "",
     las = 1)
polygon(d, col = rgb(182,207,182, alpha = 175, maxColorValue = 255), 
        border = "black", lwd = 2)
polygon(d2, col = rgb(255,255,181, alpha = 175, maxColorValue = 255), 
        border = "black", lwd = 2)

# convert to raw scale and plot - what model thinks means are
d <- density(exp(o$beta0))
d2 <- density(exp(o$beta0 + o$beta1))

plot(d,
     xlab = "Posterior distribution",
     main = "Expected no caught by sex",
     xlim = c(0,9),
     las = 1)
polygon(d, col = rgb(182,207,182, alpha = 175, maxColorValue = 255), 
        border = "black", lwd = 3)
polygon(d2, col = rgb(255,255,181, alpha = 175, maxColorValue = 255), 
        border = "black", lwd = 3)


# plot model generated new data - what model thinks data looks like
hist(o$cephs.new[,ceph_sex$FISHER_SEX == 0],
     xlab = "Cephs per catch",
     col = rgb(182,207,182, alpha = 195, maxColorValue = 255),
     main = NULL,
     xlim = c(0,18),
     breaks = 10)
hist(o$cephs.new[,ceph_sex$FISHER_SEX == 1],
     xlab = "Cephs per catch",
     col = rgb(255,255,181, alpha = 125, maxColorValue = 255),
     main = NULL,
     add = TRUE)

```

```{r yrwt, echo = FALSE}
#Linear regression

#Visualize Data-FIX THIS

plot(AVG_WT ~ YEAR, 
        ylab = "Average wt of Cepalopod",
        xlab = "Year",
        data = ceph_model)

sink("cephs_sitewt.txt")
cat(" 
    model {
    
    # PRIORS
    for(i in 1:nsites){       #loop for alphas. can also do alpha[1] alpha[2]
    alpha[i] ~ dnorm(0,0.001)
    }
    tau <- 1/sigma^2
    sigma ~ dunif(0,100) #This gives only 1 variance across all sites
    
    # LIKELIHOOD
    for(i in 1:n){
    mass[i] ~ dnorm(mu[i],tau)
    mu[i] <- alpha[site[i]] #Mean will vary by site. 3 alphas, 1 per site. loop through every row of your dataset.
    } # i
    
    # # derived quantitites
    # diff23 <- alpha[3] - alpha[2]

    # # generate new data from the fitted model
    # for(i in 1:n){
    # y.new[i] ~ dnorm(mu[i],tau)   #Generates new data for each run of mcmc
    #  }
    
    } # end of model  
    ",fill = TRUE)
sink()

win.data <- list(mass   = ceph_sites2$AVG_WT,
                 site   = ceph_sites2$id, 
                 n      = nrow(ceph_sites2),
                 nsites = length(unique(ceph_sites2$id)))

# Initial values
inits <- function()list(alpha = rnorm(7), sigma = rlnorm(1))

# Parameters monitored
params <- c("alpha",
            "sigma"
            #"Bayes.P"
            #"y.new"
) 

# MCMC settings
ni <- 1000; nt <- 3; nb <- 100; nc <- 3


out_stwt <- jags(win.data, inits, params, "cephs_sitewt.txt", 
            n.chains = nc, n.thin = nt, n.iter = ni, n.burnin = nb, 
            working.directory = getwd())
print(out_stwt, dig = 1) 


```

```{r siteno, echo = FALSE}

 #ANOVA
#Visualize Data-FIX THIS
#CHANGE TO POISSON?
boxplot(NO_CAUGHT ~ REGION, 
        ylab = "No per catch",
        xlab = "Site",
        outline = TRUE,
        notch = FALSE,
        staplewex = 0.2,
        boxwex = 0.4,
        border = TRUE,
        data = ceph_sites2)

sink("cephs_siteno.txt")
cat(" 
    model {
    
    # PRIORS
    for(i in 1:nsites){       #loop for alphas. can also do alpha[1] alpha[2]
    alpha[i] ~ dnorm(0,0.001)
    }
    tau <- 1/sigma^2
    sigma ~ dunif(0,100) #This gives only 1 variance across all sites
    
    # LIKELIHOOD
    for(i in 1:n){
    mass[i] ~ dnorm(mu[i],tau)
    mu[i] <- alpha[site[i]] #Mean will vary by site. 3 alphas, 1 per site. loop through every row of your dataset.
    } # i
    
    # # derived quantitites
    # diff23 <- alpha[3] - alpha[2]

    # # generate new data from the fitted model
    # for(i in 1:n){
    # y.new[i] ~ dnorm(mu[i],tau)   #Generates new data for each run of mcmc
    #  }
    
    } # end of model  
    ",fill = TRUE)
sink()

win.data <- list(mass   = ceph_sites2$TOT_WT,
                 site   = ceph_sites2$id, 
                 n      = nrow(ceph_sites2),
                 nsites = length(unique(ceph_sites2$id)))

# Initial values
inits <- function()list(alpha = rnorm(7), sigma = rlnorm(1))

# Parameters monitored
params <- c("alpha",
            "sigma"
            #"Bayes.P"
            #"y.new"
) 

# MCMC settings
ni <- 1000; nt <- 3; nb <- 100; nc <- 3


out_stno <- jags(win.data, inits, params, "cephs_siteno.txt", 
            n.chains = nc, n.thin = nt, n.iter = ni, n.burnin = nb, 
            working.directory = getwd())
print(out_stno, dig = 1) 


```