---
title: "BauchRhoMFig"
author: "Sophie Wulfing"
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

setwd("C:/Users/sophi/Documents/GitHub/UNH_Docs/Proposal/Soc_Ecol_Model")

library(deSolve)
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(kableExtra)


#Nest try h = .25
params_list <- data.frame(r_1 = 0.16, s_1 = 0.8, h_1 = .25, k_1 = 0.17, w_1 = 1.44, c_1 = 0.5, d_1 = 0.3, i_1 = 0, rho_1 = 0,
                          r_2 = 0.16, s_2 = 0.8, h_2 = .25, k_2 = 0.17, w_2 = 1.44, c_2 = 0.5, d_2 = 0.3, i_2 = 0, rho_2 = 0)

# #WORKED - MINIMUM GROWTH RATE USED IN THAMPI
# params_list <- data.frame(r_1 = 0.16, s_1 = 0.8, h_1 = 0.5, k_1 = 0.17, w_1 = 1.44, c_1 = 0.6, d_1 = 0.3, i_1 = 0, rho_1 = 0,
#                           r_2 = 0.16, s_2 = 0.8, h_2 = 0.5, k_2 = 0.17, w_2 = 1.44, c_2 = 0.6, d_2 = 0.3, i_2 = 0, rho_2 = 0)

#Extensions of Bauch Default but with my params I want changed. Goal: get this to oscillate
# params_list <- data.frame(r_1 = 0.35, s_1 = 0.8, h_1 = 0.5, k_1 = 0.17, w_1 = 1, c_1 = 1.68, d_1 = 0.3, i_1 = 0, rho_1 = 0,
#                           r_2 = 0.35, s_2 = 0.8, h_2 = 0.5, k_2 = 0.17, w_2 = 1, c_2 = 1.68, d_2 = 0.3, i_2 = 0, rho_2 = 0)


#Extension of Bauch Default
# params_list <- data.frame(r_1 = 0.06, s_1 = 0.8, h_1 = 0.1, k_1 = 0.17, w_1 = 1, c_1 = 0.6, d_1 = 0.3, i_1 = 0, rho_1 = 0,
#                           r_2 = 0.06, s_2 = 0.8, h_2 = 0.1, k_2 = 0.17, w_2 = 1, c_2 = 0.6, d_2 = 0.3, i_2 = 0, rho_2 = 0)


xstart <- c(F_1 = 0.406, F_2 = 0.406, X_1 = .24, X_2 = .24)
timespan <- seq(from = 0, to = 1000, by = 1)

```

```{r paramtable, results = 'asis', echo = FALSE}

giveparams <- data.frame(matrix(, nrow = 9, ncol = 4))
colnames(giveparams) <- c("Parameter", "Population_1", "Population_2", "Def")

giveparams$Parameter <- c("r", "s", "h", "k", "w", "c", "d", "i", "rho")
giveparams$Population_1 <- c(params_list[1:9])
giveparams$Population_2 <- c(params_list[10:18])

giveparams$Def <- c("Fish net growth",
                    "Supply and demand",
                    "Harvesting efficiency",
                    "Social learning rate",
                    "Conservation cost",
                    "Rarity valuation",
                    "Social norm strength (within pop)",
                    "Fish immigration (from opposite patch)",
                    "Social norm strength (opposite pop)")

knitr::kable(giveparams, format = "latex", booktabs = TRUE, caption = "Parameter values used in this analysis")

```

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r Bauch.Coupled, fig.cap = "New Model with default paramters", warning = FALSE}


##Maybe see what proportion of people can actually be fishing in this system to make it sustainable

Bauch.Coupled <- function (t, y, params) {
  ## first extract the state variables
  F_1 <- y[1] #Fish Pop var
  F_2 <- y[2] #Fish Pop var
  X_1 <- y[3] #conservationist var
  X_2 <- y[4] #conservationist var

  #TT <- y[5]
  
  ## now extract the parameters
  r_1 <- params["r_1"] # Net growth/fecundity
  s_1 <- params["s_1"] # supply and demand
  h_1 <- params["h_1"] # Harvesting efficiency
  k_1 <- params["k_1"] # Social learning rate
  w_1 <- params["w_1"] # conservation costs
  c_1 <- params["c_1"] # rarity valuation param
  d_1 <- params["d_1"] # social norm strength
  i_1 <- params["i_1"] # Inflow of fish from pop 2 to pop 1
  rho_1 <- params["rho_1"] # Influence of pop 2 on pop 1
  
  r_2 <- params["r_2"] # Net growth/fecundity
  s_2 <- params["s_2"] # supply and demand
  h_2 <- params["h_2"] # Harvesting efficiency
  k_2 <- params["k_2"] # Social learning rate
  w_2 <- params["w_2"] # conservation costs
  c_2 <- params["c_2"] # rarity valuation param
  d_2 <- params["d_2"] # social norm strength 
  i_2 <- params["i_2"] # Inflow of fish from pop 1 to pop 2
  rho_2 <- params["rho_2"] # Influence of pop 1 on pop 2
  
  ## now code the model equations
  dF_1dt <-  r_1 * F_1 * (1-F_1) - (h_1 * F_1 * (1-X_1))/(F_1+s_1) - i_2 * F_1 + i_1 * F_2
  dF_2dt <-  r_2 * F_2 * (1-F_2) - (h_2 * F_2 * (1-X_2))/(F_2+s_2) - i_1 * F_2 + i_2 * F_1
  
  dX_1dt <- k_1 * X_1 * (1-X_1) *(1/(F_1 + c_1) - w_1 + d_1*(2*X_1 - 1) + rho_1 * (2*X_2 - 1))
  dX_2dt <- k_2 * X_2 * (1-X_2) *(1/(F_2 + c_2) - w_2 + d_2*(2*X_2 - 1) + rho_2 * (2*X_1 - 1))
  
  ## combine results into a single vector
  dydt <- c(dF_1dt, dF_2dt, dX_1dt, dX_2dt)
  ## return result as a list!
  
  list(dydt)
}

params_Bauch2 <- params_list

times <- timespan
xstart <- c(F_1 = 0.406, F_2 = 0.406, X_1 = .24, X_2 = .24)

ode(
  func=Bauch.Coupled,
  y=xstart,
  times=times,
  parms=params_Bauch2
) %>%
  as.data.frame() -> out_Coupled

out_Coupled %>%
  gather(variable,value,-time) %>%
  ggplot(aes(x=time,y=value,color=variable))+
  geom_line(size=1)+
  theme_classic()+
  labs(x='time (yr)',y='pop')

```

```{r bothparams, warning = FALSE}

rhoparams <- c(0.01, 0.05, 0.1)
iparams <- c(0.01, 0.05, 0.1)
plotList <- list()
k <- 0

for(i in 1:length(iparams)){
  params_Default <- params_list
  params_Default[8] <- iparams[i]
  params_Default[17] <- iparams[i]
  
  for(j in 1:length(rhoparams)){
    k <- k+1
    params_Default[9] <- rhoparams[j]
    params_Default[18] <- rhoparams[j]
  
   times <- timespan
    xstart <- c(F_1 = 0.406, F_2 = 0.406, X_1 = .24, X_2 = .24)

    ode(
      func=Bauch.Coupled,
      y=xstart,
      times=times,
      parms=params_Default
    ) %>%
      as.data.frame() -> out_Diff

    p <- out_Diff %>%
      gather(variable,value,-time) %>%
      ggplot(aes(x=time,y=value,color=variable))+
      geom_line(size=1)+
      theme_classic()+
      labs(x='time (yr)',y='pop') +
      #theme(legend.position = "none") +
      ggtitle(paste("i = ", params_Default[8], "rho = ", params_Default[9]))
    plotList[[k]] <- p
  }
}

  
  do.call("grid.arrange", c(plotList, ncol=3))

```

```{r oneparam, warning = FALSE}

rhoparams <- c(0.01, 0.05, 0.1)
iparams <- c(0.01, 0.05, 0.1)
plotList <- list()
k <- 0

for(i in 1:length(iparams)){
  params_Default <- params_list
  params_Default[8] <- iparams[i]
  #params_Default[17] <- iparams[i]
  
  for(j in 1:length(rhoparams)){
    k <- k+1
    params_Default[9] <- rhoparams[j]
    #params_Default[18] <- rhoparams[j]
  
   times <- timespan
    xstart <- c(F_1 = 0.406, F_2 = 0.406, X_1 = .24, X_2 = .24)

    ode(
      func=Bauch.Coupled,
      y=xstart,
      times=times,
      parms=params_Default
    ) %>%
      as.data.frame() -> out_Diff

    p <- out_Diff %>%
      gather(variable,value,-time) %>%
      ggplot(aes(x=time,y=value,color=variable))+
      geom_line(size=1)+
      theme_classic()+
      labs(x='time (yr)',y='pop') +
      #theme(legend.position = "none") +
      ggtitle(paste("i1 = ", params_Default[8], "rho1 = ", params_Default[9]))
    plotList[[k]] <- p
  }
}

  
  do.call("grid.arrange", c(plotList, ncol=3))

```

```{r oppositeparams, warning = FALSE}

rhoparams <- c(0.01, 0.05, 0.1)
iparams <- c(0.01, 0.05, 0.1)
plotList <- list()
k <- 0

for(i in 1:length(iparams)){
  params_Default <- params_list
  params_Default[8] <- iparams[i]
  #params_Default[17] <- iparams[i]
  
  for(j in 1:length(rhoparams)){
    k <- k+1
    #params_Default[9] <- rhoparams[j]
    params_Default[18] <- rhoparams[j]
  
   times <- timespan
    xstart <- c(F_1 = 0.406, F_2 = 0.406, X_1 = .24, X_2 = .24)

    ode(
      func=Bauch.Coupled,
      y=xstart,
      times=times,
      parms=params_Default
    ) %>%
      as.data.frame() -> out_Diff

    p <- out_Diff %>%
      gather(variable,value,-time) %>%
      ggplot(aes(x=time,y=value,color=variable))+
      geom_line(size=1)+
      theme_classic()+
      labs(x='time (yr)',y='pop') +
      #theme(legend.position = "none") +
      ggtitle(paste("i1 = ", params_Default[8], "rho2 = ", params_Default[9]))
    plotList[[k]] <- p
  }
}

  
  do.call("grid.arrange", c(plotList, ncol=3))

```



